// apps/web-vue/modules/admin/components/user-privileges-dialog.vue
<script setup lang="ts">
import { AlertCircle } from 'lucide-vue-next';
import { useMutation } from 'villus';
import { Privilege, PRIVILEGE_LABELS } from '@repo/core';
import { UpdateUserPrivilegesDocument } from '~/api-service/generated/graphql';

const props = defineProps<{
  open: boolean;
  user: { id: string; name: string; email: string; privileges: string[] } | null;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
  saved: [];
}>();

// Ordinary authority now lives in Role. The only remaining privilege flag is the
// SUPER_ADMIN break-glass bit (see @repo/core Privilege enum).
const ALL_PRIVILEGES = [Privilege.SUPER_ADMIN] as const;

const selected = ref<number[]>([]);
const saving = ref(false);
const error = ref('');

watch(() => props.user, (u) => {
  selected.value = u ? u.privileges.map(Number) : [];
}, { immediate: true });

const { execute } = useMutation(UpdateUserPrivilegesDocument);

function togglePrivilege(priv: number) {
  if (selected.value.includes(priv)) {
    selected.value = selected.value.filter((p) => p !== priv);
  } else {
    selected.value = [...selected.value, priv];
  }
}

async function handleSave() {
  if (!props.user) return;
  saving.value = true;
  error.value = '';
  try {
    const { error: gqlError } = await execute({
      input: { userId: props.user.id, privileges: selected.value },
    });
    if (gqlError) {
      error.value = 'Failed to update privileges.';
      return;
    }
    emit('saved');
    emit('update:open', false);
  } catch {
    error.value = 'An error occurred.';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>Edit Privileges</DialogTitle>
      </DialogHeader>

      <div v-if="user" class="space-y-4">
        <p class="text-sm text-gray-500">
          User: <span class="font-medium text-gray-900 dark:text-white">{{ user.name }}</span>
          ({{ user.email }})
        </p>

        <div class="space-y-2">
          <label
            v-for="priv in ALL_PRIVILEGES"
            :key="priv"
            class="flex cursor-pointer items-center gap-3 rounded-md border border-gray-200 p-3 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800"
          >
            <Checkbox
              :checked="selected.includes(priv)"
              @update:checked="togglePrivilege(priv)"
            />
            <span class="text-sm font-medium">{{ PRIVILEGE_LABELS[priv] ?? priv }}</span>
          </label>
        </div>
        <p class="text-xs text-gray-400">
          Privileges are break-glass flags. Grant everyday access through Roles instead.
        </p>

        <Alert v-if="error" variant="destructive">
          <AlertCircle class="size-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{{ error }}</AlertDescription>
        </Alert>
      </div>

      <DialogFooter>
        <Button variant="ghost" @click="emit('update:open', false)">Cancel</Button>
        <Button :disabled="saving" @click="handleSave">
          <span v-if="saving" class="flex items-center gap-2">
            <span class="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Saving...
          </span>
          <span v-else>Save Changes</span>
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// apps/frontend/src/modules/admin/users/components/user-privileges-dialog.tsx
'use client';

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@repo/ui/components/dialog';
import { Button } from '@repo/ui/components/button';
import { Checkbox } from '@repo/ui/components/checkbox';
import { Badge } from '@repo/ui/components/badge';
import { toast } from 'sonner';
import { Privilege } from '@repo/core';
import { updateUserPrivileges } from '@/api-service/mutations/update-user-privileges';
import type { UserListItem } from '../hooks/use-users-data';

// Privileges now carry only SUPER_ADMIN (a break-glass bypass). All ordinary
// authority (borrower / lender / admin) is granted through roles — use the
// "Manage Roles" dialog for that.
const PRIVILEGE_OPTIONS = [
  {
    value: Privilege.SUPER_ADMIN,
    label: 'Super Admin',
    description: 'Break-glass: full system access, bypasses RBAC',
    tier: 'admin',
  },
] as const;

interface Props {
  open: boolean;
  user: UserListItem | null;
  onClose: () => void;
  onUpdated: () => void;
}

export function UserPrivilegesDialog({ open, user, onClose, onUpdated }: Props) {
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (open && user) {
      setSelected(new Set(user.privileges ?? []));
    }
  }, [open, user]);

  function toggle(value: number) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });
  }

  async function handleSave() {
    if (!user) return;
    setSubmitting(true);
    try {
      await updateUserPrivileges({ userId: user.id, privileges: Array.from(selected) });
      toast.success('Privileges updated', { description: `Updated privileges for ${user.email}` });
      onUpdated();
      onClose();
    } catch (err: any) {
      toast.error('Failed to update', { description: err?.message ?? 'Unknown error' });
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Edit Privileges</DialogTitle>
          {user && <p className="text-sm text-muted-foreground">{user.email}</p>}
        </DialogHeader>

        <div className="space-y-4">
          <p className="text-xs text-muted-foreground">
            Privileges carry only the break-glass Super Admin flag. Grant ordinary borrower / lender /
            admin authority through <span className="font-medium">Manage Roles</span> instead.
          </p>
          <div className="space-y-2">
            {PRIVILEGE_OPTIONS.map((opt) => (
              <label
                key={opt.value}
                className="flex items-start gap-3 rounded-md border p-3 cursor-pointer hover:bg-accent/50 transition-colors"
              >
                <Checkbox
                  checked={selected.has(opt.value)}
                  onCheckedChange={() => toggle(opt.value)}
                  className="mt-0.5"
                />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium">{opt.label}</span>
                    <Badge variant="outline" className="text-[10px]">
                      {opt.value}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground">{opt.description}</p>
                </div>
              </label>
            ))}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={submitting}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={submitting}>
            {submitting ? 'Saving...' : 'Save Privileges'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
