// apps/web-vue/modules/auth/components/verify-code-form.vue
<script setup lang="ts">
import { AlertCircle } from 'lucide-vue-next';
import { TwoFactorMethod } from '~/api-service/generated/graphql';

interface Props {
  method: TwoFactorMethod;
  email: string;
  loading: boolean;
  error: string;
  isLockedOut: boolean;
  isResending: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  (e: 'submit', code: string): void;
  (e: 'resend'): void;
}>();

const code = ref('');

function onSubmit() {
  if (code.value.length !== 6) return;
  emit('submit', code.value);
}
</script>

<template>
  <form @submit.prevent="onSubmit" class="space-y-4">
    <div class="space-y-1.5">
      <Label for="verify-code">
        {{ props.method === TwoFactorMethod.TOTP ? 'Authenticator code' : 'Email verification code' }}
      </Label>
      <Input
        id="verify-code"
        v-model="code"
        type="text"
        inputmode="numeric"
        autocomplete="one-time-code"
        maxlength="6"
        placeholder="000000"
        :disabled="props.loading || props.isLockedOut"
        class="text-center text-2xl tracking-widest font-mono"
        required
      />
      <p v-if="props.method === TwoFactorMethod.EMAIL" class="text-xs text-muted-foreground">
        Code sent to {{ props.email }}. Check your inbox (or server logs in dev).
      </p>
      <p v-else class="text-xs text-muted-foreground">
        Open your authenticator app and enter the 6-digit code.
      </p>
    </div>

    <Alert v-if="props.isLockedOut" variant="destructive">
      <AlertCircle class="size-4" />
      <AlertTitle>Locked out</AlertTitle>
      <AlertDescription>
        Too many failed attempts. Try again in 10 minutes.
      </AlertDescription>
    </Alert>

    <Alert v-else-if="props.error" variant="destructive">
      <AlertCircle class="size-4" />
      <AlertTitle>Error</AlertTitle>
      <AlertDescription>{{ props.error }}</AlertDescription>
    </Alert>

    <Button type="submit" class="w-full" :disabled="props.loading || props.isLockedOut || code.length !== 6">
      <span v-if="props.loading" class="flex items-center gap-2">
        <span class="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
        Verifying...
      </span>
      <span v-else>Verify</span>
    </Button>

    <Button
      v-if="props.method === TwoFactorMethod.EMAIL"
      type="button"
      variant="ghost"
      class="w-full"
      :disabled="props.isResending || props.isLockedOut"
      @click="emit('resend')"
    >
      <span v-if="props.isResending">Sending...</span>
      <span v-else>Resend code</span>
    </Button>
  </form>
</template>

// apps/frontend/src/modules/auth/login-verify/components/verify-code-form.tsx
'use client';

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@repo/ui/components/button';
import { Input } from '@repo/ui/components/input';
import type { TwoFactorChallenge } from '@/store/modules/auth/auth-types';
import { TwoFactorMethod } from '@/api-service/generated/graphql.generated';

const verifySchema = z.object({
  code: z
    .string()
    .length(6, 'Code must be 6 digits')
    .regex(/^\d{6}$/, 'Code must be numeric'),
});

type VerifyFormValues = z.infer<typeof verifySchema>;

interface VerifyCodeFormProps {
  challenge: TwoFactorChallenge;
  isLoading: boolean;
  serverError: string | null;
  isLockedOut: boolean;
  onSubmit: (code: string) => void;
  onResend: () => void;
  isResending: boolean;
}

export function VerifyCodeForm({
  challenge,
  isLoading,
  serverError,
  isLockedOut,
  onSubmit,
  onResend,
  isResending,
}: VerifyCodeFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<VerifyFormValues>({
    resolver: zodResolver(verifySchema),
  });

  const disabled = isSubmitting || isLoading || isLockedOut;

  const handleFormSubmit = (values: VerifyFormValues) => {
    onSubmit(values.code);
  };

  const methodLabel =
    challenge.method === TwoFactorMethod.TOTP
      ? 'Enter the 6-digit code from your authenticator app'
      : `Enter the 6-digit code sent to ${challenge.email}`;

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-4">
      <p className="text-sm text-muted-foreground">{methodLabel}</p>

      <div className="space-y-1">
        <label htmlFor="code" className="text-sm font-medium">
          Verification code
        </label>
        <Input
          id="code"
          type="text"
          inputMode="numeric"
          maxLength={6}
          placeholder="000000"
          disabled={disabled}
          autoComplete="one-time-code"
          className="tracking-[0.5em] text-center text-lg"
          {...register('code')}
        />
        {errors.code && <p className="text-xs text-destructive">{errors.code.message}</p>}
      </div>

      {serverError && <p className="text-sm text-destructive">{serverError}</p>}

      {isLockedOut && (
        <p className="text-sm text-destructive font-medium">
          Too many failed attempts. Please wait and try again.
        </p>
      )}

      <Button type="submit" className="w-full" disabled={disabled}>
        {isSubmitting || isLoading ? 'Verifying…' : 'Verify'}
      </Button>

      {challenge.method === TwoFactorMethod.EMAIL && (
        <div className="text-center">
          <button
            type="button"
            onClick={onResend}
            disabled={isResending || isLockedOut}
            className="text-sm text-primary hover:underline disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isResending ? 'Sending…' : 'Resend code'}
          </button>
        </div>
      )}
    </form>
  );
}
