// apps/frontend/src/modules/admin/api-keys/components/create-api-key-dialog.tsx
'use client';

import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@repo/ui/components/dialog';
import { Button } from '@repo/ui/components/button';
import { Input } from '@repo/ui/components/input';
import { Label } from '@repo/ui/components/label';
import { Checkbox } from '@repo/ui/components/checkbox';
import { ScrollArea } from '@repo/ui/components/scroll-area';
import { Copy, Check } from 'lucide-react';
import { useRoles } from '../../permissions/hooks/use-roles-data';
import type { CreateApiKeyInput, ApiKeyOutput } from '../hooks/use-api-keys-data';

interface Props {
  open: boolean;
  onClose: () => void;
  onCreate: (input: CreateApiKeyInput) => Promise<ApiKeyOutput>;
}

export function CreateApiKeyDialog({ open, onClose, onCreate }: Props) {
  const { roles, loading: loadingRoles, fetch: fetchRoles } = useRoles();

  const [name, setName] = useState('');
  const [selectedRoleIds, setSelectedRoleIds] = useState<Set<string>>(new Set());
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [createdKey, setCreatedKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (open) {
      fetchRoles();
      setName('');
      setSelectedRoleIds(new Set());
      setError(null);
      setCreatedKey(null);
      setCopied(false);
    }
  }, [open, fetchRoles]);

  function toggleRole(id: string) {
    setSelectedRoleIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function handleSubmit() {
    if (!name.trim()) {
      setError('Name is required');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const result = await onCreate({
        name: name.trim(),
        roleIds: selectedRoleIds.size > 0 ? Array.from(selectedRoleIds) : undefined,
      });
      if (result.key) {
        setCreatedKey(result.key);
      } else {
        onClose();
      }
    } catch (err: any) {
      setError(err?.response?.errors?.[0]?.message ?? err?.message ?? 'Failed to create API key');
    } finally {
      setSubmitting(false);
    }
  }

  async function handleCopy() {
    if (!createdKey) return;
    try {
      await navigator.clipboard.writeText(createdKey);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback: select input text
    }
  }

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>New API Key</DialogTitle>
        </DialogHeader>

        {createdKey ? (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Copy your API key now — it will not be shown again.
            </p>
            <div className="space-y-1.5">
              <Label>API Key</Label>
              <div className="flex gap-2">
                <Input readOnly value={createdKey} className="font-mono text-xs" />
                <Button variant="outline" size="icon" onClick={handleCopy} aria-label="Copy key">
                  {copied ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
                </Button>
              </div>
            </div>
            <DialogFooter>
              <Button onClick={onClose}>Done</Button>
            </DialogFooter>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label htmlFor="key-name">Name *</Label>
              <Input
                id="key-name"
                placeholder="e.g. CI/CD Pipeline Key"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>

            <div className="space-y-1.5">
              <Label>Roles (optional)</Label>
              <ScrollArea className="h-40 rounded border p-3">
                {loadingRoles ? (
                  <p className="text-sm text-muted-foreground">Loading…</p>
                ) : roles.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No roles available.</p>
                ) : (
                  <div className="space-y-2">
                    {roles.map((role) => (
                      <div key={role.id} className="flex items-center gap-2">
                        <Checkbox
                          id={`role-${role.id}`}
                          checked={selectedRoleIds.has(role.id)}
                          onCheckedChange={() => toggleRole(role.id)}
                        />
                        <label htmlFor={`role-${role.id}`} className="cursor-pointer text-sm font-mono">
                          {role.name}
                        </label>
                      </div>
                    ))}
                  </div>
                )}
              </ScrollArea>
            </div>

            {error && <p className="text-sm text-destructive">{error}</p>}

            <DialogFooter>
              <Button variant="outline" onClick={onClose} disabled={submitting}>
                Cancel
              </Button>
              <Button onClick={handleSubmit} disabled={submitting}>
                {submitting ? 'Creating…' : 'Create Key'}
              </Button>
            </DialogFooter>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

// apps/web-vue/modules/admin/components/create-api-key-dialog.vue
<script setup lang="ts">
import { AlertCircle, AlertTriangle, Check, Copy, Key } from 'lucide-vue-next';
import { useMutation, useQuery } from 'villus';
import { GetAccessPoliciesDocument, CreateApiKeyDocument } from '~/api-service/generated/graphql';

const props = defineProps<{
  open: boolean;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
  created: [];
}>();

const { data: policiesData } = useQuery({ query: GetAccessPoliciesDocument });
const { execute: createKey } = useMutation(CreateApiKeyDocument);

const availablePolicies = computed(() => policiesData.value?.getAccessPolicies?.data ?? []);

const keyName = ref('');
const selectedPolicies = ref<string[]>([]);
const saving = ref(false);
const error = ref('');
const generatedKey = ref('');
const copied = ref(false);

watch(() => props.open, (val) => {
  if (!val) {
    keyName.value = '';
    selectedPolicies.value = [];
    error.value = '';
    generatedKey.value = '';
    copied.value = false;
  }
});

function togglePolicy(id: string) {
  selectedPolicies.value = selectedPolicies.value.includes(id)
    ? selectedPolicies.value.filter((p) => p !== id)
    : [...selectedPolicies.value, id];
}

async function handleCreate() {
  if (!keyName.value.trim()) { error.value = 'Name is required.'; return; }
  saving.value = true;
  error.value = '';
  try {
    const { data, error: gqlError } = await createKey({
      input: { name: keyName.value, policyIds: selectedPolicies.value },
    });
    if (gqlError || !data?.createApiKey?.data) {
      error.value = 'Failed to create API key.';
      return;
    }
    generatedKey.value = data.createApiKey.data.key;
    emit('created');
  } catch {
    error.value = 'An error occurred.';
  } finally {
    saving.value = false;
  }
}

async function copyKey() {
  if (!generatedKey.value) return;
  await navigator.clipboard.writeText(generatedKey.value);
  copied.value = true;
  setTimeout(() => { copied.value = false; }, 2000);
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>Create API Key</DialogTitle>
      </DialogHeader>

      <div class="space-y-4">
        <!-- Creation form -->
        <div v-if="!generatedKey" class="space-y-4">
          <div class="space-y-1.5">
            <Label>Key Name</Label>
            <div class="relative">
              <Key class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input v-model="keyName" placeholder="e.g. my-integration" class="pl-9" />
            </div>
          </div>

          <div>
            <p class="mb-2 text-sm font-medium">Assign Policies</p>
            <div class="max-h-48 space-y-2 overflow-y-auto">
              <label
                v-for="policy in availablePolicies"
                :key="policy.id"
                class="flex cursor-pointer items-center gap-3 rounded-md border border-gray-200 p-2.5 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800"
              >
                <Checkbox
                  :checked="selectedPolicies.includes(policy.id)"
                  @update:checked="togglePolicy(policy.id)"
                />
                <span class="text-sm">{{ policy.name }}</span>
              </label>
              <p v-if="availablePolicies.length === 0" class="text-sm text-gray-400">No policies available.</p>
            </div>
          </div>

          <Alert v-if="error" variant="destructive">
            <AlertCircle class="size-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{{ error }}</AlertDescription>
          </Alert>
        </div>

        <!-- Generated key display -->
        <div v-else class="space-y-3">
          <Alert>
            <AlertTriangle class="size-4" />
            <AlertTitle>Copy this key now</AlertTitle>
            <AlertDescription>It won't be shown again.</AlertDescription>
          </Alert>
          <div class="flex items-center gap-2 rounded-md border border-gray-200 p-3 dark:border-gray-700">
            <code class="flex-1 break-all text-xs">{{ generatedKey }}</code>
            <Button variant="ghost" size="icon" class="size-8 shrink-0" @click="copyKey">
              <Check v-if="copied" class="size-4 text-green-500" />
              <Copy v-else class="size-4" />
            </Button>
          </div>
        </div>
      </div>

      <DialogFooter>
        <Button variant="ghost" @click="emit('update:open', false)">Close</Button>
        <Button v-if="!generatedKey" :disabled="saving" @click="handleCreate">
          <span v-if="saving" class="flex items-center gap-2">
            <span class="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Generating...
          </span>
          <span v-else>Generate Key</span>
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
