// apps/web-vue/modules/admin/components/role-dialog.vue
<script setup lang="ts">
import { AlertCircle } from 'lucide-vue-next';
import { useMutation } from 'villus';
import { CreateRoleDocument, UpdateRoleDocument } from '~/api-service/generated/graphql';

const props = defineProps<{
  open: boolean;
  editingRole: { id: string; name: string; description: string } | null;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
  saved: [];
}>();

const name = ref('');
const description = ref('');
const saving = ref(false);
const error = ref('');

const isEdit = computed(() => !!props.editingRole);

watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) {
      name.value = props.editingRole?.name ?? '';
      description.value = props.editingRole?.description ?? '';
      error.value = '';
    }
  },
  { immediate: true },
);

const { execute: createRole } = useMutation(CreateRoleDocument);
const { execute: updateRole } = useMutation(UpdateRoleDocument);

async function handleSave() {
  const trimmed = name.value.trim();
  if (!trimmed) {
    error.value = 'Role name is required.';
    return;
  }
  saving.value = true;
  error.value = '';
  try {
    const desc = description.value.trim() || undefined;
    const { error: gqlError } = props.editingRole
      ? await updateRole({ id: props.editingRole.id, input: { name: trimmed, description: desc } })
      : await createRole({ input: { name: trimmed, description: desc, permissionKeys: [] } });
    if (gqlError) {
      error.value = gqlError.message || 'Failed to save role.';
      return;
    }
    emit('saved');
    emit('update:open', false);
  } catch {
    error.value = 'An error occurred.';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>{{ isEdit ? 'Edit Role' : 'New Role' }}</DialogTitle>
      </DialogHeader>

      <div class="space-y-4">
        <div class="space-y-2">
          <Label for="role-name">Name</Label>
          <Input id="role-name" v-model="name" placeholder="e.g. lender_operator" />
        </div>
        <div class="space-y-2">
          <Label for="role-description">Description</Label>
          <Input id="role-description" v-model="description" placeholder="Optional description" />
        </div>

        <Alert v-if="error" variant="destructive">
          <AlertCircle class="size-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{{ error }}</AlertDescription>
        </Alert>
      </div>

      <DialogFooter>
        <Button variant="ghost" @click="emit('update:open', false)">Cancel</Button>
        <Button :disabled="saving" @click="handleSave">
          <span v-if="saving" class="flex items-center gap-2">
            <span class="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Saving...
          </span>
          <span v-else>{{ isEdit ? 'Save Changes' : 'Create Role' }}</span>
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// apps/frontend/src/modules/admin/permissions/components/role-dialog.tsx
'use client';

import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@repo/ui/components/dialog';
import { Button } from '@repo/ui/components/button';
import { Input } from '@repo/ui/components/input';
import { Label } from '@repo/ui/components/label';
import type { RoleItem } from '@/store/modules/admin/permissions/permissions-types';

export interface RoleFormValue {
  name: string;
  description?: string;
}

interface Props {
  open: boolean;
  onClose: () => void;
  onCreate: (value: RoleFormValue) => void | Promise<void>;
  role?: RoleItem;
  onUpdate?: (id: string, value: RoleFormValue) => void | Promise<void>;
}

/**
 * Create / rename a role. Permission assignment happens in the matrix on the
 * page — this dialog only owns identity (name + description).
 */
export function RoleDialog({ open, onClose, onCreate, role, onUpdate }: Props) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (open && role) {
      setName(role.name);
      setDescription(role.description ?? '');
    } else if (open && !role) {
      setName('');
      setDescription('');
    }
    setError(null);
  }, [open, role]);

  async function handleSubmit() {
    if (!name.trim()) {
      setError('Name is required');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const value: RoleFormValue = {
        name: name.trim(),
        description: description.trim() || undefined,
      };
      if (role && onUpdate) await onUpdate(role.id, value);
      else await onCreate(value);
      onClose();
    } catch (err: any) {
      setError(err?.response?.errors?.[0]?.message ?? err?.message ?? 'Operation failed');
    } finally {
      setSubmitting(false);
    }
  }

  const isEditMode = !!role;

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>{isEditMode ? 'Edit Role' : 'New Role'}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="role-name">Name *</Label>
            <Input
              id="role-name"
              placeholder="e.g. lender_operator"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="role-desc">Description</Label>
            <Input
              id="role-desc"
              placeholder="Optional description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          {isEditMode && (
            <p className="text-xs text-muted-foreground">
              Assign permissions in the matrix after saving.
            </p>
          )}

          {error && <p className="text-sm text-destructive">{error}</p>}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={submitting}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={submitting}>
            {submitting
              ? isEditMode
                ? 'Saving…'
                : 'Creating…'
              : isEditMode
                ? 'Save Changes'
                : 'Create Role'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
